server:
  port: 8761
  servlet:
    context-path: /
eureka:
  environment: product
  server:
    # 关闭自我保护
    enable-self-preservation: false
#    # 清理服务器
#    eviction-interval-timer-in-ms: 5000
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
spring:
  security:
    basic:
      enabled: true
    user:
      name: user
      password: password